version: '3.8'

services:
  app:
    container_name: classconnect_container
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
  db:
    image: postgres:15
    container_name: classconnect_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: